version: '3.3'
services:
    server:
        container_name: bt
        environment:
            - SIGNUPS_ALLOWED=true
            - WEBSOCKET_ENABLED=true
            - ROCKET_WORKERS=40
            - 'DOMAIN=https://bt.26hk.cn'
            - SMTP_HOST=smtp.office365.com
            - SMTP_FROM=hk@clarifyffg.onmicrosoft.com
            - SMTP_PORT=587
            - SMTP_SECURITY=starttls
            - SMTP_USERNAME=hk@clarifyffg.onmicrosoft.com
            - SMTP_PASSWORD=7SobJRJ3SC7Xpx
            - 'ADMIN_TOKEN=@8yJ9pYp*Xz43z%F'
        volumes:
            - '/www/wwwroot/bt.26hk.cn/:/data/'
        ports:
            - '80:80'
            - '3012:3012'
        image: 'vaultwarden/server:latest'
